In [2]:
import numpy as np # type: ignore


1. Create a 3x3 array that contains a diagonal of nines.


In [11]:
arr1=np.diag([9,9,9])
print(arr1)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


Create a 4 x 4 ndarray that only contains consecutive even numbers from 2 to 32 (inclusive) 
and use boolean indexing to pick out the values that are within 1/2 standard deviations of the mean.

In [12]:
arr2=np.arange(2,34,2).reshape(4,4)
mean=arr2.mean()
std=arr2.std()

within_half_std = arr2[(arr2 >= mean - 0.5 * std) &
                        (arr2 <= mean + 0.5 * std)]
print("4x4 ndarray with consecutive even numbers:\n", arr2)
print("Values within 1/2 standard deviations of the mean:\n", within_half_std)


4x4 ndarray with consecutive even numbers:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]
Values within 1/2 standard deviations of the mean:
 [14 16 18 20]


3. Create a 9x9 array that contains only zeros of type int.

In [13]:
arr3=np.zeros((9,9), dtype=int)
print(arr3)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]



4. Ask the user for a number n. Then, use broadcasting to create a n x n ndarray that has its

 first column full of ones, its second column full of twos, its third column full of threes, etc…


In [25]:
n = int(input("Enter the value of n: "))
arr4= np.arange(1, n + 1).reshape(1, n) * np.ones((n, 1), dtype=int)
print(arr4)

https://codeforces.com/contest/707/problem/A

In [4]:


# Read input
n = int(input())
cards = np.array(list(map(int, input().split())))

# Initialize scores
sereja_score = 0
dima_score = 0

# Initialize turn flag
turn_sereja = True

# Game simulation
while cards.size > 0:
    # Determine the larger value from the ends
    if cards[0] > cards[-1]:
        chosen_card = cards[0]
        cards = cards[1:]  # Remove the leftmost card
    else:
        chosen_card = cards[-1]
        cards = cards[:-1]  # Remove the rightmost card
    
    # Assign the chosen card's value to the current player
    if turn_sereja:
        sereja_score += chosen_card
    else:
        dima_score += chosen_card
    
    # Alternate turns
    turn_sereja = not turn_sereja

# Print the final scores
print(sereja_score, dima_score)


ValueError: invalid literal for int() with base 10: ''

https://codeforces.com/contest/707/problem/A

In [ ]:
import numpy as np

# Read the dimensions of the matrix
n, m = map(int, input().split())

# Initialize the matrix
matrix = np.array([input().split() for _ in range(n)])

# Define the set of colored pixels
colored_pixels = {'C', 'M', 'Y'}

# Check if any element in the matrix is a colored pixel
is_colored = np.isin(matrix, list(colored_pixels)).any()

# Print the result based on the presence of colored pixels
if is_colored:
    print("#Color")
else:
    print("#Black&White")
